# Generated by Django 4.2.3 on 2023-07-04 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Anubis', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signup',
            old_name='Signuppass',
            new_name='password1',
        ),
        migrations.RenameField(
            model_name='signup',
            old_name='Signupname',
            new_name='uname',
        ),
    ]
