# Generated by Django 4.2.3 on 2023-07-04 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Anubis', '0002_rename_signuppass_signup_password1_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
        migrations.DeleteModel(
            name='Signup',
        ),
    ]
