# Generated by Django 4.2.2 on 2023-11-30 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Anubis', '0003_delete_login_delete_signup'),
    ]

    operations = [
        migrations.CreateModel(
            name='CameraDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('url', models.URLField()),
            ],
        ),
    ]
