# Generated by Django 4.2.3 on 2025-04-21 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Anubis', '0005_camera'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Camera',
        ),
    ]
